sudo: false
language:
- java
script:
- "travis_wait mvn -pl quickfixj-codegenerator install"
- "travis_wait mvn -pl quickfixj-dictgenerator install"
- "travis_wait mvn -pl quickfixj-core install"
jdk:
- oraclejdk8
env:
- MAVEN_OPTS="-Xms2048m -Xmx=2048m"
branches:
  only:
    - travis-ci-build
