sudo: false
language:
    - java
install:
  - mvn validate
script: 
  - travis_wait mvn -T4 -pl quickfixj-codegenerator install
jdk:
  - oraclejdk8
env:
  - MAVEN_OPTS="-Xms2048m -Xmx=2048m"
branches:
  only:
    - travis-ci-build

