sudo: false
language:
    - java
install:
  - mvn --version
script: 
  - travis_wait mvn -T4 clean install -Dskip.jalopy -DskipTests=true -Dmaven.javadoc.skip=true --debug
jdk:
  - oraclejdk8
env:
  - MAVEN_OPTS="-Xmx=512m"
branches:
   only:
     - travis-ci-build
