sudo: false
language:
    - java
install:
  - mvn --version
script:
  - travis_wait 30 mvn install -e -X -Dskip.jalopy -DskipTests=true -Dmaven.javadoc.skip=true 
jdk:
  - oraclejdk8
env:
  - MAVEN_OPTS="-Xmx=1024m"
branches:
   only:
     - travis-ci-build
