sudo: false
language:
    - java
install:
  - mvn --version
script: 
  - travis_wait 30 mvn -T4 install -Dskip.jalopy -DskipTests=true -Dmaven.javadoc.skip=true
jdk:
  - oraclejdk8
env:
  - MAVEN_OPTS="-Xms3072m -Xmx=3072m"
branches:
  only:
    - travis-ci-build

