sudo: false
language:
    - java
install:
  - mvn --version
script: 
  - mvn -T4 install -Dskip.jalopy -DskipTests=true -Dmaven.javadoc.skip=true
jdk:
  - oraclejdk8
env:
  - MAVEN_OPTS="-Xmx=512m"
branches:
  only:
    - travis-ci-build

