sudo: false
language:
    - java
install:
  - mvn --version
script: 
  - mvn -T4 install -Dskip.jalopy -DskipTests=true -Dmaven.javadoc.skip=true -Xmx=512m --debug
jdk:
  - oraclejdk8
branches:
  only:
    - travis-ci-build

